/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A730SG33ht6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Skillzz() {
  return (
    <section className="py-12 md:py-16 lg:py-20">
      <div className="container px-4 md:px-6">
        <div className="mb-8 md:mb-12 lg:mb-16 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">
            My Skills
          </h2>
        </div>
        <div className="grid grid-cols-2 gap-6 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">
          <div className="flex flex-col items-center gap-2">
            <img
              alt="ts"
              className="h-12 w-12 text-primary"
              height={48}
              src="/typescript.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Typescript</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Vue"
              className="h-12 w-12 text-primary"
              height={48}
              src="/javascript.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Javascript</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="java"
              className="h-12 w-12 text-primary"
              height={48}
              src="/java.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Java</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="python"
              className="h-12 w-12 text-primary"
              height={48}
              src="/python.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Python</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="go"
              className="h-12 w-12 text-primary"
              height={48}
              src="/go.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Go</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="JavaScript"
              className="h-12 w-12 text-primary"
              height={48}
              src="/c.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">C++</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="tailwind"
              className="h-12 w-12 text-primary"
              height={48}
              src="/tailwind.jpeg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Tailwind</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="react"
              className="h-12 w-12 text-primary"
              height={48}
              src="/react.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">React</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="nextjs"
              className="h-12 w-12 text-primary"
              height={48}
              src="/nextjs.webp"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Next.js</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="nodejs"
              className="h-12 w-12 text-primary"
              height={48}
              src="/node-js.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Node.js</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="express"
              className="h-12 w-12 text-primary"
              height={48}
              src="/express-js.png"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Express</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="postman"
              className="h-12 w-12 text-primary"
              height={48}
              src="/postman.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Postman</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Prisma"
              className="h-12 w-12 text-primary"
              height={48}
              src="/prisma.avif"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Prisma</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Git"
              className="h-12 w-12 text-primary"
              height={48}
              src="/postgresql.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Postgresql</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="GitHub"
              className="h-12 w-12 text-primary"
              height={48}
              src="/mongodb.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">MongoDB</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Figma"
              className="h-12 w-12 text-primary"
              height={48}
              src="/mysql.png"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">MySQL</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Photoshop"
              className="h-12 w-12 text-primary"
              height={48}
              src="/amazon-aws.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">AWS</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="cloudflare"
              className="h-12 w-12 text-primary"
              height={48}
              src="/cloudflare.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Cloudflare</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Illustrator"
              className="h-12 w-12 text-primary"
              height={48}
              src="/docker.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Docker</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Illustrator"
              className="h-12 w-12 text-primary"
              height={48}
              src="/kubernaties.png"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Kubernaties</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="terraform"
              className="h-12 w-12 text-primary"
              height={48}
              src="/terraform.png"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Terrraform</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Ansible"
              className="h-12 w-12 text-primary"
              height={48}
              src="/ansible.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Ansible</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="ci/cd"
              className="h-12 w-12 text-primary"
              height={48}
              src="/jenkins.webp"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">CI/CD</span>
          </div>

          <div className="flex flex-col items-center gap-2">
            <img
              alt="linux"
              className="h-12 w-12 text-primary"
              height={48}
              src="/linux.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Linux</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="git"
              className="h-12 w-12 text-primary"
              height={48}
              src="/git.svg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Git</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="scripting"
              className="h-12 w-12 text-primary"
              height={48}
              src="/script.jpg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Scripting</span>
          </div>

          <div className="flex flex-col items-center gap-2">
            <img
              alt="soketpng"
              className="h-12 w-12 text-primary"
              height={48}
              src="/soket.png"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Socket.io</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="zod"
              className="h-12 w-12 text-primary"
              height={48}
              src="/zod.jpg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">ZOD</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Illustrator"
              className="h-12 w-12 text-primary"
              height={48}
              src="/jwt.jpg"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">JWT Auth</span>
          </div>
          <div className="flex flex-col items-center gap-2">
            <img
              alt="Illustrator"
              className="h-12 w-12 text-primary"
              height={48}
              src="/turbo-logo.png"
              style={{
                aspectRatio: "48/48",
                objectFit: "cover",
              }}
              width={48}
            />
            <span className="text-sm font-medium">Turborepo</span>
          </div>
        </div>
      </div>
    </section>
  )
}
