/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hP7HNpK7j0J
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import kubernaties from "@/public/kubernaties.png"
import js from "@/public/javascript.svg"

export function Skills() {
  return (
    <section className="w-full py-12 md:py-24 dark">
      <div className="container grid max-w-3xl items-start gap-4 px-4 md:px-6 lg:gap-8 xl:max-w-5xl">
        <div className="space-y-2 text-center pb-20">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl ">
            Skills
          </h2>
          <p className="text-gray-500 mx-auto max-w-[600px] dark:text-gray-300">
            I have got the skills to pay the bills.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Typescript"
                className="rounded-xl border"
                height="48"
                src="/typescript.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Typescript</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/javascript.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Javascript</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Frontend"
                className="rounded-xl border"
                height="48"
                src="/java.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Java</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Backend"
                className="rounded-xl border"
                height="48"
                src="/python.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Python</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="go"
                className="rounded-xl border"
                height="48"
                src="/go.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Go</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="c++"
                className="rounded-xl border"
                height="48"
                src="/c.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">C++</h3>
            </div>
          </div>

          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Tailwind"
                className="rounded-xl border"
                height="48"
                src="/tailwind.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Tailwind</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="React"
                className="rounded-xl border"
                height="48"
                src="/react.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">React</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Nextjs"
                className="rounded-xl border"
                height="48"
                src="/next-js.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Next.js</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Cloud Computing"
                className="rounded-xl border"
                height="48"
                src="/node-js.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Node.js</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/express.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Express</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/prism.png"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Prisma</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/mongodb.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">MongoDB</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/postgresql.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Postgres</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/sql.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">MySQL</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/amazon-aws.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">AWS</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/cloudflare.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Cloudflare</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/docker.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Docker</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/kubernaties.png"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Kubernaties</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="terraform"
                className="rounded-xl border"
                height="48"
                src="/terraform.png"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Terraform</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/postman.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Postman</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/ansible.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Ansible</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/linux.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Linux</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/git.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Git</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/script.jpg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Scripting</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Socket.io</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/jenkins.png"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>

            <div className="space-y-1.5">
              <h3 className="font-semibold">CI/CD</h3>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
