/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hP7HNpK7j0J
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import kubernaties from "@/public/kubernaties.png"

export function Skills() {
  return (
    <section className="w-full py-12 md:py-24 dark">
      <div className="container grid max-w-3xl items-start gap-4 px-4 md:px-6 lg:gap-8 xl:max-w-5xl">
        <div className="space-y-2 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
            Skills & Expertise
          </h2>
          <p className="text-gray-500 mx-auto max-w-[600px] dark:text-gray-400">
            I've got the skills to pay the bills.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Design"
                className="rounded-xl border"
                height="48"
                src="/kubernaties.png"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Creative Design</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Frontend"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Frontend Magic</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Backend"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Backend Wizardry</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Mobile"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Mobile Mastery</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="SEO"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">SEO Expert</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Data Analysis"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Data Analysis</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Security"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Security Expertise</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Automation"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Automation Skills</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="Cloud Computing"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">Cloud Computing</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
          <div className="flex items-start space-x-4">
            <div className="w-12 h-12 flex-shrink-0 rounded-xl overflow-hidden">
              <img
                alt="UX"
                className="rounded-xl border"
                height="48"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "48/48",
                  objectFit: "cover",
                }}
                width="48"
              />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-semibold">User Experience</h3>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
